### ISSUE TITLE
Plus sign in email addresse seems not to be allowed

### ISSUE THREAD

**Issue by RincewindsHat** [Alovoa/alovoa-android#16]
Having a plus sign `+` in the email address gets silently rejected (App doesn't do anything) when trying to log in.

Version from Fdroid.

**Comment by Nonononoki** [comment]
I think you're on the wrong repo, this is the repo for Alovoa Lite. For The Alovoa (non-Lite), please go here: https://github.com/Alovoa/alovoa-expo. Bug is known is willö be fixed in version 1.4.2.

**Comment by RincewindsHat** [comment]
ah sorry, my fault. Looked right repo. Sorry for the noice
