### ISSUE TITLE
Notification bar doean't change color after accent change

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa-android#7]
If you chamge the accent color in the alovoa for example into the blue color,  the title bar remains the pink color and doesn't change into the blue color.

it would probably look better if it followed accent color.

**Comment by Nonononoki** [comment]
The status bar color is currently hard coded in the manifest. I don't think it's possible to change the status bar color dynamically.

https://github.com/Alovoa/alovoa-android/blob/cd53a139a4ec3f0b198cfdf8bcdd65fa229cc2fc/app/src/main/AndroidManifest.xml#L25-L27
